### ISSUE TITLE
Allow running as arbitrary user

### ISSUE THREAD

**Issue by Magissia** [lhmouse/sudo-win#1]
On Linux, sudo does not only elevate, it allows, depending on configuration, to allow restricted users to run specific binaries as arbitrary users, not necessarily root.

Are there future plans to get to this point, or will this tool stay to a state of [elevate.exe](https://www.winability.com/info/elevate/) ?

**Comment by lhmouse** [comment]
I don't think following the behavior of Linux `sudo` is an option, because:

1. On Linux, after a program is sudo'd it inherits the std{in,out,err} streams from the parent shell, no matter whether it is running as root or not, which is not possible on Windows unless you are already in an elevated console. For security reasons windows of an elevated process cannot interact with those of a non-elevated process.
2. `sudo` without any parameters just produces an error, while `sudo-win` in this case works exactly the same as `sudo -i`. There is no `-u` option whatsoever.

The goal of `sudo-win` is to keep itself _as tiny as possible_. The program makes no use of CRT functions (only WinAPIs) hence can be built with `-nostdlib`. For this reason, there is no complex command line parsing.

If the original post is a musthave for you, open a PR please.

**Comment by lhmouse** [comment]
I am closing this issue for now. This can be reopened in the future as needed.
